public with sharing class CSVDataObject {

        @AuraEnabled 
        public String column01;
    
        @AuraEnabled 
        public String column02;
    
        @AuraEnabled 
        public String column03;
    
        @AuraEnabled 
        public String column04;
    
        @AuraEnabled 
        public String column05;
    
        @AuraEnabled 
        public String column06;
    
        @AuraEnabled 
        public String column07;
    
        @AuraEnabled 
        public String column08;
    
        @AuraEnabled 
        public String column09;
    
        @AuraEnabled 
        public String column10;
    
        @AuraEnabled 
        public String column11;
    
        @AuraEnabled 
        public String column12;
    
        @AuraEnabled 
        public String column13;
    
        @AuraEnabled 
        public String column14;
    
        @AuraEnabled 
        public String column15;
    
        @AuraEnabled 
        public String column16;
    
        @AuraEnabled 
        public String column17;
    
        @AuraEnabled 
        public String column18;
    
        @AuraEnabled 
        public String column19;
    
        @AuraEnabled 
        public String column20;

        @AuraEnabled 
        public String column21;
    
        @AuraEnabled 
        public String column22;
    
        @AuraEnabled 
        public String column23;
    
        @AuraEnabled 
        public String column24;
    
        @AuraEnabled 
        public String column25;
    
        @AuraEnabled 
        public String column26;
    
        @AuraEnabled 
        public String column27;
    
        @AuraEnabled 
        public String column28;
    
        @AuraEnabled 
        public String column29;
    
        @AuraEnabled 
        public String column30;
    
        @AuraEnabled 
        public String column31;
    
        @AuraEnabled 
        public String column32;
    
        @AuraEnabled 
        public String column33;

        @AuraEnabled 
        public String column34;
    
        @AuraEnabled 
        public String column35;
    
        @AuraEnabled 
        public String column36;
    
        @AuraEnabled 
        public String column37;
    
        @AuraEnabled 
        public String column38;
    
        @AuraEnabled 
        public String column39;
    
        @AuraEnabled 
        public String column40;
    
}


